### ISSUE TITLE
cond variable assignment

### ISSUE THREAD

**Issue by xudindin** [hejingwenhejingwen/CResMD#7]
hi, jingwen, a quick question.

[test.py Line57](https://github.com/hejingwenhejingwen/CResMD/blob/master/codes/test.py#L57) cond variable is repeatedly divided by cond_norm, making itself rapidly decreasing to 0. Is it correct?

**Comment by hejingwenhejingwen** [comment]
Actually, the cond variable contains several conditions, and each condition correponds to different degradations. Since different degradatioins have different ranges, the conditons are normalized to [0, 1] with different parameters (cond_norm). The cond variable could be '0' when the corresponding degradation doesn't exit.
